import React from 'react'
import Link from "next/link";
import Head from "next/head";

const Navbar = () => {
  return (
    <>
    <Head>
        <title>Dev Scout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
          crossorigin="anonymous"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
       <nav className="navbar  navbar-expand-lg navbar-light  text-center">
          <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <ul className="navbar-nav mx-auto">
              <li className="nav-item"  >
                <Link className="nav-link" href="/">
                 Home   
                 
                </Link>
              </li>
              <li className="nav-item ">
                <Link className="nav-link" href="/about">
                  About 
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" href="/blog">
                  Blogs
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" href="/contact">
                  Contact
                </Link>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    </>
    
  )
}

export default Navbar
