import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Dev Scout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
          crossorigin="anonymous"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div>
        <main className={styles.main}>
          <h1 className={styles.title}>Hunting Coders</h1>
          <div className="imgWrapper">
            {/* <Image src= "/homeImg.avif" width={600} height={400} alt="coding Image"></Image> */}
            <img
              src="/homeImg.avif"
              alt="Hunting coders"
              width={600} height={400}
              className={styles.homeImg}
            />
          </div>
          <h2 className={styles.description}>
            A blog for hunting coders by coder
          </h2>
          
          <div className={styles.ctas}></div>
        </main>
      </div>
    </>
  );
}
